name: Dependency Updates

on:
  schedule:
    # Run weekly on Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-supabase-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for Supabase CLI updates
        id: check-cli
        run: |
          # Get latest Supabase CLI version
          LATEST=$(curl -s https://api.github.com/repos/supabase/cli/releases/latest | grep -o '"tag_name": "v[^"]*"' | cut -d'"' -f4 | sed 's/v//')
          echo "latest_version=$LATEST" >> $GITHUB_OUTPUT
          echo "Latest Supabase CLI version: $LATEST"

      - name: Generate update report
        run: |
          echo "## Dependency Update Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Supabase CLI" >> $GITHUB_STEP_SUMMARY
          echo "Latest version: \`${{ steps.check-cli.outputs.latest_version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "To update locally, run:" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "supabase upgrade" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  update-deno:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for Deno updates
        id: check-deno
        run: |
          LATEST=$(curl -s https://api.github.com/repos/denoland/deno/releases/latest | grep -o '"tag_name": "v[^"]*"' | cut -d'"' -f4)
          echo "latest_version=$LATEST" >> $GITHUB_OUTPUT
          echo "Latest Deno version: $LATEST"

      - name: Read current Deno version
        id: current-deno
        run: |
          CURRENT=$(grep "deno_version" supabase/config.toml | grep -o '[0-9]*' || echo "2")
          echo "current_version=$CURRENT" >> $GITHUB_OUTPUT

      - name: Generate Deno update report
        run: |
          echo "## Deno Version Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Current major version: \`${{ steps.current-deno.outputs.current_version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "Latest available: \`${{ steps.check-deno.outputs.latest_version }}\`" >> $GITHUB_STEP_SUMMARY

  check-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for outdated GitHub Actions
        run: |
          echo "## GitHub Actions Update Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Current Actions" >> $GITHUB_STEP_SUMMARY

          # List all used actions
          grep -r "uses:" .github/workflows/ | sed 's/.*uses: /- /' | sort -u >> $GITHUB_STEP_SUMMARY || echo "No actions found"

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Recommendations" >> $GITHUB_STEP_SUMMARY
          echo "- Review [GitHub Actions marketplace](https://github.com/marketplace?type=actions) for updates" >> $GITHUB_STEP_SUMMARY
          echo "- Check for major version updates to actions used" >> $GITHUB_STEP_SUMMARY
