name: Security Scanning

on:
  push:
    branches:
      - master
      - main
  pull_request:
  schedule:
    # Run weekly on Wednesday at 3 AM UTC
    - cron: '0 3 * * 3'

jobs:
  secret-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

  dependency-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  sql-injection-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for SQL injection vulnerabilities
        run: |
          echo "Scanning for potential SQL injection patterns..."

          # Check for string concatenation in SQL files
          if grep -r "||" supabase/migrations/ 2>/dev/null | grep -v "-- "; then
            echo "⚠️  Warning: String concatenation found in SQL files"
            echo "Consider using parameterized queries"
          fi

          # Check for dynamic SQL
          if grep -r "EXECUTE.*||" supabase/migrations/ 2>/dev/null; then
            echo "⚠️  Warning: Dynamic SQL execution found"
            echo "Review for potential SQL injection risks"
          fi

      - name: Generate security report
        if: always()
        run: |
          echo "## Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Security scans completed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Scans Performed" >> $GITHUB_STEP_SUMMARY
          echo "- Secret scanning (TruffleHog)" >> $GITHUB_STEP_SUMMARY
          echo "- Dependency scanning (Trivy)" >> $GITHUB_STEP_SUMMARY
          echo "- SQL injection pattern check" >> $GITHUB_STEP_SUMMARY
